apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector: # Seleciona o flask-app para expor
    app: flask-app
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  type: LoadBalancer
